### ISSUE TITLE
The 'quantity' field should be a whole number

### ISSUE THREAD

**Issue by deriise** [mollie/OpenCart#160]
Error executing API call (422: Unprocessable Entity): Order line 1 is invalid. Error executing API call (422: Unprocessable Entity): Order line 1 is invalid. The 'quantity' field should be a whole number. Field: lines.1.quantity.

I get this message because i'm trying to sell half products (example: 0,55 meters of fabric). Is there a way around this? 

somebody closed this, but it is still a problem for me

**Comment by QualityWorks** [comment]
This should have been fixed in 9.1.0. this is why I closed the issue. Can you please check again on this version?

**Comment by deriise** [comment]
http://mollie.rijshosting.com 
Still not working. this website is a clean install.

**Comment by QualityWorks** [comment]
This has been fixed in the latest release(s)
