### ISSUE TITLE
Custom CSS fields error

### ISSUE THREAD

**Issue by beireken** [mollie/OpenCart#226]
In Mollie settings all Custom CSS input fields contain an error string as following example:

`<b>Warning</b>: Illegal string offset 'background_color' in <b>/var/www/html/opencart/admin/view/template/payment/mollie.tpl</b> on line <b>432</b><b>Notice</b>: Uninitialized string offset: 0 in <b>/var/www/html/opencart/admin/view/template/payment/mollie.tpl</b> on line <b>432</b>`

**Comment by QualityWorks** [comment]
this is solved in the newest release

**Comment by beireken** [comment]
Still an issue after updating to 9,4,0 using the built-in updater.
