### ISSUE TITLE
Fatal error with Mollie 10.0.1 & OpenCart 3.0.3.6

### ISSUE THREAD

**Issue by TriumphDesign** [mollie/OpenCart#246]
Hi,

Getting fatal error. The error is on the checkout page:

`Fatal error: Uncaught Exception: Error: Could not load model extension/payment/mollie_creditcard! in /home/customer/www/docusv.sg-host.com/storage/modification/system/engine/loader.php:89 Stack trace: #0 /home/customer/www/docusv.sg-host.com/public_html/catalog/controller/checkout/payment_method.php(51): Loader->model('extension/payme...') #1 /home/customer/www/docusv.sg-host.com/storage/modification/system/engine/action.php(79): ControllerCheckoutPaymentMethod->index() #2 /home/customer/www/docusv.sg-host.com/public_html/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) #3 /home/customer/www/docusv.sg-host.com/storage/modification/system/engine/action.php(79): ControllerStartupRouter->index() #4 /home/customer/www/docusv.sg-host.com/public_html/system/engine/router.php(67): Action->execute(Object(Registry)) #5 /home/customer/www/docusv.sg-host.com/public_html/system/engine/router.php(56): Router->execute(Object(Action)) #6 /home/customer/www/docusv.sg-host.com/public_html/system/framework.php(1 in /home/customer/www/docusv.sg-host.com/storage/modification/system/engine/loader.php on line 89`

Using the OCMod version

Hope you can help me with this.
Cheers,

**Comment by QualityWorks** [comment]
hello,
if you go into the mollie module in admin and save the settings, this should be fixed.

**Comment by TriumphDesign** [comment]
Hi, thanks for the quick reply, this doesn't solve the problem. Sadly.

**Comment by QualityWorks** [comment]
you did refresh the modifications?

**Comment by TriumphDesign** [comment]
Yes

**Comment by beireken** [comment]
same error here

**Comment by Kukiwon** [comment]
I'm seeing the same error. Refreshing and saving the settings did not work for me either.

**Comment by QualityWorks** [comment]
this should all be fixed in 10.1.0, just upload the files from the zip, and optionally, remove the files from storage/modification if you are experiencing errors. (and after you login again, refresh modifications)
