### ISSUE TITLE
HTTP error 500 when editing any of the mollie settings

### ISSUE THREAD

**Issue by kionaJ** [mollie/OpenCart#335]
Hi,

Mollie is nor working anymore. In the backend it is ginving a 500
And in frontend there cannot be done any payement
Opencart version: 3.0.2.0
Mollie version I do not know where to find the version.
All is active but a soon as I want to edit a mollie I get a 500 error

Can you help?
Thanks

**Comment by QualityWorks** [comment]
please update the mollie module through ftp using the latest release. this should fix it

**Comment by kionaJ** [comment]
Hi,

I updated the Mollie but problem still exists.

Can you help me?
